project_name: lock

before:
  hooks:
    - go mod tidy

builds:
  - id: lock
    main: ./cmd/lock
    binary: lock
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: lock-archive
    builds:
      - lock
    formats:
      - tar.gz
    name_template: "lock_darwin_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true
