project_name: lock

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "0.0.0-dev+{{ .ShortCommit }}"

builds:
  - id: lock
    main: ./cmd/lock
    binary: lock
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: lock-archive
    builds:
      - lock
    formats:
      - tar.gz
    name_template: "lock_darwin_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true
